import {Dimensions, StyleSheet} from 'react-native';
//import {Colors} from 'react-native/Libraries/NewAppScreen';

export const styles = StyleSheet.create({
  container: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    //marginTop: 50,
  },
  imageViewerContainer: {
    backgroundColor: 'white',
    height: '100%',
    marginTop: 50,
    padding: 5,
  },
  imageContainer: {
    height: '90%',
    marginTop: 430,
    marginLeft: 50,
  },
  image: {
    margin: 5,
    width: 100,
    height: 100,
  },
  button: {
    width: 180,
    height: 60,
    backgroundColor: 'black',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  buttonText: {
    textAlign: 'center',
    fontSize: 25,
    color: '#fff',
  },
  imageBack: {
    width: 100,
    height: 100,
    borderRadius: 50,
    margin: 5,
  },
  üstbanner: {
    flexDirection: 'row',
  },
  ustbanner2: {
    flexDirection: 'column',
    marginLeft: 10,
  },
  kullaniciAdi: {
    fontSize: 18,
    marginTop: 10,
  },
  imageYildiz: {
    width: 110,
    height: 15,
    marginTop: 10,
  },
  degerlendirme: {
    marginTop: 45,
    fontSize: 15,
  },
  buttonGenel: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  box: {
    width: 200,
    height: 30,
    backgroundColor: '#e5e5e5',
    borderRadius: 7,
  },
  cerceve: {
    backgroundColor: '#fff',
    marginHorizontal: 10,
    marginVertical: 10,
    borderRadius: 5,
    paddingVertical: 20,
    paddingHorizontal: 10,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 3,
  },
  iconOzellik: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 20,
  },
  input: {
    height: 75,
    paddingHorizontal: 5,
    borderWidth: 2,
    borderRadius: 4,
    borderColor: '#f1f1f1',
    color: '#999',
    marginBottom: 12,
    fontSize: 18,
    fontWeight: '600',
  },
  SecimEkraniContainer: {
    flex: 1,
    marginTop: 10,
    margin: 'auto',
  },
  ustBaslik: {
    borderWidth: 1,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderColor: 'black',
    marginTop: 10,
  },
  ileri: {
    //marginLeft: 385,
    marginTop: -30,
    //paddingTop: 25,
    //margin: 'auto',
    paddingLeft: 380,
  },
  galeriSecme: {
    marginTop: 80,
    marginLeft: -35,
    marginBottom: -85,
  },
  kapat: {
    //margin: 'auto',
    marginTop: -10,
  },
  aciklamaContainer: {
    flex: 1,
  },
  urunBasligi: {
    height: 105,
    marginHorizontal: 5,
    marginVertical: 140,
    backgroundColor: 'white',
    //#dcdcdc
    borderRadius: 5,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    marginTop: 10,
  },
  urunBasligiText: {
    fontSize: 20,
    marginTop: 20,
    marginLeft: 5,
  },
  inputUrunBasligi: {
    height: 105,
    paddingHorizontal: 5,
    borderWidth: 2,
    borderRadius: 4,
    borderColor: '#dcdcdc',
    shadowColor: '#dcdcdc',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    color: '#999',
    marginBottom: 12,
    fontSize: 18,
    fontWeight: '600',
  },
  urunAciklama: {
    height: 155,
    marginHorizontal: 5,
    marginVertical: 140,
    backgroundColor: 'white',
    //#dcdcdc
    borderRadius: 5,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    marginTop: -70,
  },
  inputAciklama: {
    height: 155,
    paddingHorizontal: 5,
    borderWidth: 2,
    borderRadius: 4,
    borderColor: '#dcdcdc',
    shadowColor: '#dcdcdc',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    color: '#999',
    marginBottom: 12,
    fontSize: 18,
    fontWeight: '600',
    //marginHorizontal: 5,
    //marginVertical: 140,
    //marginTop: -70,
  },
  urunAciklamaText: {
    fontSize: 20,
    marginLeft: 5,
    marginTop: -28,
  },
  inputFiyat: {
    backgroundColor: 'white',
    height: 55,
    paddingHorizontal: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: '#dcdcdc',
    shadowColor: '#dcdcdc',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    color: '#999',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    marginTop: 5,
    marginHorizontal: 5,
  },
  urunFiyatText: {
    fontSize: 20,
    marginLeft: 5,
    marginTop: -100,
  },
  OnizlemeEkraniContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  FotografEkrani: {
    backgroundColor: 'white',
    height: 135,
    paddingHorizontal: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: '#dcdcdc',
    shadowColor: '#dcdcdc',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    color: '#999',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    marginTop: 7,
    marginHorizontal: 5,
  },
  EkleDuzenle: {
    marginLeft: 300,
    marginTop: -20,
  },
  BaslikKontrol: {
    backgroundColor: 'white',
    height: 75,
    paddingHorizontal: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: '#dcdcdc',
    shadowColor: '#dcdcdc',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    color: '#999',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    marginTop: 5,
    marginHorizontal: 5,
  },
  AciklamaKontrol: {
    backgroundColor: 'white',
    height: 105,
    paddingHorizontal: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: '#dcdcdc',
    shadowColor: '#dcdcdc',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    color: '#999',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    marginTop: 5,
    marginHorizontal: 5,
  },
  KategoriKontrol: {
    backgroundColor: 'white',
    height: 75,
    paddingHorizontal: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: '#dcdcdc',
    shadowColor: '#dcdcdc',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    color: '#999',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    marginTop: 5,
    marginHorizontal: 5,
  },
  FiyatKontrol: {
    backgroundColor: 'white',
    height: 75,
    paddingHorizontal: 5,
    borderWidth: 2,
    borderRadius: 5,
    borderColor: '#dcdcdc',
    shadowColor: '#dcdcdc',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    color: '#999',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
    marginTop: 5,
    marginHorizontal: 5,
  },
  Onay: {
    backgroundColor: 'red',
    width: '100%',
    height: 40,
  },
});
